name: Create PFX
runs:
  using: "composite"
  steps:
    - run: |
        New-Item -ItemType file -Path ./key.txt
        Set-Content -Path ./key.txt -Value $env:PfxBase64
        certutil -decode ./key.txt ./key.pfx
      shell: powershell
