name: Test Product
description: Run the Pester tests for a given product
inputs:
  Thumbprint:
    required: true
    description: "The certificate thumbprint"
  Alias:
    required: true
    description: "The alias of the product being tested"
  TestParams:
    required: true
    description: "The set of parameters used to defined the test"
outputs:
  passed:
    description: "Count of tests that passed"
    value: ${{ steps.run-test.outputs.passed }}
  failed:
    description: "Count of tests that failed"
    value: ${{ steps.run-test.outputs.failed }}
  skipped:
    description: "Count of tests that were skipped"
    value: ${{ steps.run-test.outputs.skipped }}
  total:
    description: "Total count of executed tests"
    value: ${{ steps.run-test.outputs.total }}
runs:
  using: "composite"
  steps:
    - id: run-test
      run: |
        Import-Module -Name Selenium
        cd repo

        . utils/action/Test-Product.ps1
        Test-Product `
          -Thumbprint "${{ inputs.Thumbprint }}" `
          -ProductAlias "${{ inputs.Alias }}" `
          -TestParams "${{ inputs.TestParams }}"
      shell: powershell
