name: Import Modules
description: Import the modules required to run ScubaGear
runs:
  using: "composite"
  steps:
    - run: |
        # Install Selenium
        Import-Module -Name .\repo\utils\workflow\Install-SeleniumForTesting
          Install-SeleniumForTesting
        # Setup ScubaGear
        Import-Module -Name .\repo\utils\workflow\Initialize-ScubaGearForTesting
          Initialize-ScubaGearForTesting
      shell: powershell
