name: "\U0001F41B Bug report"
description: Describe a bug, error, unexpected behavior, or other problem
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: This issue has an informative and human-readable title.
          required: true
  - type: textarea
    attributes:
      label: ScubaGear Version
      description: Which ScubaGear version are you using?
      placeholder: |
        Run Invoke-SCuBA -Version locally and paste output here to ensure correct version is indicated.
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: |
        Enter your operating system and version (e.g., Windows 10, Ubuntu 24.04 LTS, MacOS Big Sur)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: PowerShell Version
      description: Which PowerShell version are you using?
      options:
        - "5.1"
        - "7.0+"
    validations:
      required: true
  - type: textarea
    attributes:
      label: M365 Environment and License(s)
      description: Which M365 environment and license type(s) are you using?
      placeholder: |
        M365 Environment: gcc, gcc high, dod, etc.
        License type: Microsoft 365 E3/E5, G3/G5, Microsoft Defender for Office 365 Plan 1 & 2, Microsoft Entra P1/P2, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "\U0001F41B Summary"
      description: What's wrong? Please be specific.
      placeholder: Seeing unexpected results in the reports...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior. Any helpful log output or screenshots?
      placeholder: |
        1. Do this
        2. Then this

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen that didn't?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output from Initialize-SCuBA (optional)
      description: |
        Paste the results here:
      placeholder: "Tip: Run Initialize-SCuBA on the client where you are running ScubaGear and copy/paste the output here."
    validations:
      required: false
