name: "\U0001F41B Bug report"
description: Describe a bug, error, unexpected behavior, or other problem
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
      - label: This issue has an informative and human-readable title.
        required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: PowerShell Version
      description: Which PowerShell version are you using?
      placeholder: Enter PowerShell version (e.g., 5.1, 7.0)
    validations:
      required: true
  - type: textarea
    attributes:
      label: "\U0001F41B Summary"
      description: What's wrong? Please be specific.
      placeholder: Seeing unexpected results in the reports...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Do this
        2. Then this
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen that didn't?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any helpful log output or screenshots? (optional)
      description: |
        Paste the results here:
      placeholder: "Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in."
    validations:
      required: false
