name: Extract Email
description: Extract the emails to notify on failure
outputs:
  emails:
    value: ${{ steps.emails-output.outputs.emails }}
runs:
  using: "composite"
  steps:
    - run: |
        Write-Host "Extracting email..."
        $productAlias = $env:Alias
        Write-Host "The product alias is"
        Write-Host $productAlias
        $params = $env:TestParams
        $products = $params.split("|")
        foreach ($product in $products)
        {
          Write-Host "The product is"
          Write-Host $product
          [String]$emails = ""
          $attributes = $product.split(",")
          foreach ($attribute in $attributes)
          {
            # Split the key from the value
            $keyAndValue = $attribute.split("=")
            $key = $keyAndValue[0]
            $value = $keyAndValue[1]
            if($key.ToLower() -eq "alias")
            {
              $alias = $value
            }
            elseif($key.ToLower() -eq "emails")
            {
              Write-Host "Found the emails"
              $emails = $value
            }
          }
          if($alias -eq $productAlias)
          {
            # Pass emails to later job for notification.
            Write-Host "The emails:"
            Write-Host $emails
            echo emails=$emails >> $env:GITHUB_OUTPUT
          }
          break
        }
      id: emails-output
      shell: powershell
