# ScubaGear Configuration File 
# Generated on: 2026-03-04 11:55:23 

# Organization Configuration 
Organization: jeffersonlab.onmicrosoft.com 
OrgName: DOE 
OrgUnitName: DOE-SC-JLAB 
Description: Jefferson Lab 

# Configuration Details 
ProductNames: 
  - aad 
  - exo 
  - sharepoint 
  - teams 
M365Environment: gcc 

# Advanced Settings 
#  Baseline Control: Output Configuration 
OutPath: "C:\\Users\\mitchelbaker\\Documents\\Github\\ScubaGear\\M365BaselineConformance"
OutFolderName: M365BaselineConformance 
OutProviderFileName: ProviderSettingsExport 
OutRegoFileName: TestResults 
OutReportName: BaselineReports 
OutJsonFileName: ScubaResults 
OutCsvFileName: ScubaResults 
OutActionPlanFileName: ActionPlan 
#  Baseline Control: General Settings 
LogIn: true 
DisconnectOnExit: false 