name: Get Thumbprint
runs:
  using: "composite"
  steps:
    - run: |
        Write-Host "files"
        dir
        $x509 = Get-PfxCertificate -FilePath ./key.pfx -Password (ConvertTo-SecureString -String $env:PfxPassword -AsPlainText -Force)
        Write-Host "x"
        Write-Host $x509
        $Thumbprint = $x509.ThumbPrint
        # Pass thumbprint to later job.
        echo "The tp is"
        echo tp
        echo thumbprint=$Thumbprint >> $env:GITHUB_OUTPUT
      # -Password flag requires PS 6+
      shell: pwsh
