# Purpose: The purpose of this workflow is to delete all caches in the repo, as it has limited total cache storage.
# Warning: This can disrupt other workflows that are using caches. Run with caution.

name: Clear Caches

on:
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache list
          cacheKeys=$(gh actions-cache list -R $REPO)
          set +e
          for cacheKey in $cacheKeys
          do
            gh actions-cache delete $cacheKey --confirm
          done
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
