on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sudo apt install gh -y
          gh extension install actions/gh-actions-cache
          cacheKeys=$(gh actions-cache list)
          set +e
          for cacheKey in $cacheKeys
          do
            gh actions-cache delete $cacheKey --confirm
          done
        env:
          GH_TOKEN: ${{ github.token }}