name: Bump Dependencies File PowerShell Dependencies
# This workflow bumps the PowerShell dependencies in the dependencies.psd1 file in the root directory.
# It runs on a schedule and can also be triggered manually.
# The workflow uses the PSScriptAnalyzer and PSDepend modules to analyze and update the dependencies.

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (if needed)
        run: |
          pwsh -Command "if (-not (Get-Module -ListAvailable -Name PSScriptAnalyzer)) { Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser }"
          pwsh -Command "if (-not (Get-Module -ListAvailable -Name PSDepend)) { Install-Module -Name PSDepend -Force -Scope CurrentUser }"

      - name: Bump PowerShell dependencies
        run: |
          pwsh -File ./WorkflowScripts/PsDependenciesRoot.ps1

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./dependencies.psd1
          git commit -m 'Bump PowerShell dependencies' || echo "No changes to commit"
          git push
