# Purpose:  Test a solution to the concurrency issues for the nightly production functional tests

# NOTE:  This is intended to be a temporary workflow.

name: Test Concurrency with Nightly Functional Tests

on:
  schedule:
    - cron: "15 4 * * 0-4"
  workflow_dispatch:
    inputs:
      # checkov:skip=CKV_GHA_7:Manual inputs are desired.
      email-on-failure:
        description: Check to send an email on failure
        type: boolean
        required: true
        default: false
  # For debugging only
  push:
    paths:
      - ".github/workflows/test_concurrency.yaml"
      - ".github/actions/**"

permissions: read-all

env:
  GalleryName: PrivateScubaGearGallery

jobs:
  publish:
    name: Publish to Private Gallery
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Install Azure Signing Tool
        run: |
          dotnet --version
          dotnet tool install --global AzureSignTool --version 5.0.0
      # OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Get Key Vault Info
        id: key-vault-info
        env:
          KEY_VAULT_INFO: ${{ secrets.SCUBA_KEY_VAULT_PROD}}
        run: |
          $KeyVaultInfo = ${env:KEY_VAULT_INFO} | ConvertFrom-Json
          echo "KeyVaultUrl=$($KeyVaultInfo.KeyVault.URL)" >> $env:GITHUB_OUTPUT
          echo "KeyVaultCertificateName=$($KeyVaultInfo.KeyVault.CertificateName)" >> $env:GITHUB_OUTPUT
      - name: Create Private Gallery
        run: |
          # Source the deploy utilities so the functions in it can be called.
          . repo/utils/workflow/Publish-ScubaGear.ps1
          cd repo
          New-PrivateGallery -GalleryName $env:GalleryName -Trusted
      - name: Sign and Publish Module
        run: |
            # Source the deploy utilities so the functions in it can be called.
            . repo/utils/workflow/Publish-ScubaGear.ps1
            # Remove non-release files
            Remove-Item -Recurse -Force repo -Include .git*
            # Setup the parameters
            $Parameters = @{
              AzureKeyVaultUrl = '${{ steps.key-vault-info.outputs.KeyVaultUrl }}'
              CertificateName = '${{ steps.key-vault-info.outputs.KeyVaultCertificateName }}'
              ModuleSourcePath = 'repo/PowerShell/ScubaGear'
              GalleryName = $env:GalleryName
            }
            # This publishes to a private gallery, from which we will pull in a future step.
            # This step helps us verify that ScubaGear is in a state where it can be
            # published to PSGallery.
            Publish-ScubaGearModule @Parameters
      - name: Test Module Publish
        run: |
          Get-Location
          $TestContainers = @()
          $TestContainers += New-PesterContainer -Path "repo/Testing/Functional/BuildTest" -Data @{ }
          $PesterConfig = @{
            Run = @{
              Container = $TestContainers
            }
            Output = @{
              Verbosity = 'Detailed'
            }
          }
          $Config = New-PesterConfiguration -Hashtable $PesterConfig
          Invoke-Pester -Configuration $Config
      # This is a manual test that simply writes the version to the console.
      - name: Print Scuba Version
        run: |
          cd repo
          Install-Module -Name ScubaGear -Repository $env:GalleryName -SkipPublisherCheck
          Import-Module -Name ./utils/workflow/Initialize-ScubaGearForTesting
          Initialize-ScubaGearForTesting
          Invoke-SCuBA -Version
          Test-Path -Path "C:\Program Files\WindowsPowerShell\Modules\ScubaGear"
      - name: Install Selenium
        run: |
          Import-Module -Name .\repo\utils\workflow\Install-SeleniumForTesting
          Install-SeleniumForTesting
      # Instead of initializing ScubaGear repeated for each of the test jobs below,
      # we cache the PowerShell modules and OPA here and then restore them for the jobs.
      # It's about a 20% performance improvement.
      - name: Cache ScubaGear
        id: scubagear-directory
        uses: actions/cache/save@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: "scubagear-directory-${{ github.run_id }}"
      - name: Cache Dependencies
        id: powershell-directory
        uses: actions/cache/save@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: "powershell-directory-${{ github.run_id }}"
      - name: Cache OPA
        id: opa-directory
        uses: actions/cache/save@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: "opa-directory-${{ github.run_id }}"
  # Tms_Tenant1:
  #   name: Test Teams on Tenant 1
  #   runs-on: windows-latest
  #   environment: Development
  #   permissions:
  #     id-token: write
  #     contents: write
  #   concurrency:
  #     group: Tms_Tenant1
  #     cancel-in-progress: false
  #   needs:
  #     - publish
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #       with:
  #         path: repo
  #     - name: Import PFX
  #       uses: ./repo/.github/actions/import-pfx
  #       env:
  #         PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
  #         PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
  #     - name: Get Thumbprint
  #       id: get-thumbprint
  #       uses: ./repo/.github/actions/get-thumbprint
  #       env:
  #         PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
  #     - name: Restore ScubaGear
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
  #         key: scubagear-directory-
  #     - name: Restore Dependencies
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
  #         key: powershell-directory-
  #     - name: Restore OPA
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Users\runneradmin\.scubagear\Tools
  #         key: opa-directory-
  #     - name: Test
  #       id: test-product
  #       uses: ./repo/.github/actions/test-product
  #       env:
  #         Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
  #         Alias: Tms_Tenant1
  #         TestParams: ${{ secrets.NIGHTLY_TEST_BUILD_PARAMS }}
  #     - name: Notify on Failure
  #       if: ${{ failure() && (inputs.email-on-failure || github.event.schedule || github.event_name == 'push') }}
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         username: ${{ secrets.NOTIFIER_EMAIL_USERNAME }}
  #         password: ${{ secrets.NOTIFIER_EMAIL_PASSWORD }}
  #         subject: Nightly functional test failure
  #         body: The Tms_Tenant1 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
  #         to: ${{ steps.test-product.outputs.emails }}
  #         from: ScubaGear Notifier
  # Ent_Tenant1:
  #   name: Test Entra on Tenant 1
  #   runs-on: windows-latest
  #   environment: Development
  #   permissions:
  #     id-token: write
  #     contents: write
  #   concurrency:
  #     group: Ent_Tenant1
  #     cancel-in-progress: false
  #   needs:
  #     - publish
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #       with:
  #         path: repo
  #     - name: Import PFX
  #       uses: ./repo/.github/actions/import-pfx
  #       env:
  #         PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
  #         PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
  #     - name: Get Thumbprint
  #       id: get-thumbprint
  #       uses: ./repo/.github/actions/get-thumbprint
  #       env:
  #         PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
  #     - name: Restore ScubaGear
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
  #         key: scubagear-directory-
  #     - name: Restore Dependencies
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
  #         key: powershell-directory-
  #     - name: Restore OPA
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: C:\Users\runneradmin\.scubagear\Tools
  #         key: opa-directory-
  #     - name: Test
  #       id: test-product
  #       uses: ./repo/.github/actions/test-product
  #       env:
  #         Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
  #         Alias: Ent_Tenant1
  #         TestParams: ${{ secrets.NIGHTLY_TEST_BUILD_PARAMS }}
  #     - name: Notify on Failure
  #       if: ${{ failure() && (inputs.email-on-failure || github.event.schedule || github.event_name == 'push') }}
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         username: ${{ secrets.NOTIFIER_EMAIL_USERNAME }}
  #         password: ${{ secrets.NOTIFIER_EMAIL_PASSWORD }}
  #         subject: Nightly functional test failure
  #         body: The Tms_Tenant1 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
  #         to: ${{ steps.test-product.outputs.emails }}
  #         from: ScubaGear Notifier
  cleanup:
    name: Clear Caches
    runs-on: ubuntu-latest
    permissions: write-all
    # needs:
    #   - publish
      # - Ent_Tenant1
      # - Tms_Tenant1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          echo "Installing actions-cache"
          gh extension install actions/gh-actions-cache
          echo "Creating keys"
          $keys=@(
            'scubagear-directory-' + ${{ github.run_id }} 'powershell-directory-' + ${{ github.run_id }}'opa-directory-' + ${{ github.run_id }}
          )
          echo "Looping"
          for $key in $keys
          do
            echo $key
            cacheKeys=$(gh actions-cache list -R $REPO --key $key)
            set +e
            for $cacheKey in $cacheKeys
            do
              gh actions-cache delete $cacheKey --confirm
            done
          done
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
