# Purpose:  Test a solution to the concurrency issues for the nightly production functional tests
# NOTE:  This is intended to be a temporary workflow

name: Test Concurrency with Nightly Functional Tests

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test_concurrency.yaml"
      - ".github/actions"

permissions: read-all

jobs:
  Ent_Tenant1:
    name: Test Ent_Tenant1
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: powershell
    concurrency:
      group: aad
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Create PFX
        uses: ./.github/actions/create-pfx
        env:
          PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
      - name: Import PFX
        uses: ./.github/actions/import-pfx
        env:
          PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
      - name: Get Thumbprint
        uses: ./.github/actions/get-thumbprint
        env:
          PfxPassword: ${{ secrets.NIGHTLY_TEST_BUILD_PW }}
  # Ent_Tenant2_G3:
  #   name: Test Ent_Tenant2_G3
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: powershell
  #   concurrency:
  #     group: aad
  #     cancel-in-progress: false
  #   needs:
  #     - Ent_Tenant1
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #     - name: Create PFX
  #       uses: ./.github/actions/create-pfx
  #       env:
  #         PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
  # Def_Tenant1:
  #   name: Test Def_Tenant1
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: powershell
  #   concurrency:
  #     group: defender
  #     cancel-in-progress: false
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #     - name: Create PFX
  #       uses: ./.github/actions/create-pfx
  #       env:
  #         PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
  # Def_Tenant2_G3:
  #   name: Test Def_Tenant2_G3
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: powershell
  #   concurrency:
  #     group: defender
  #     cancel-in-progress: false
  #   needs:
  #     - Def_Tenant1
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #     - name: Create PFX
  #       uses: ./.github/actions/create-pfx
  #       env:
  #         PfxBase64: ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
