# Purpose:  Test a solution to the concurrency issues for the nightly production functional tests
# NOTE:  This is intended to be a temporary workflow

name: Test Concurrency with Nightly Functional Tests

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test_concurrency.yaml"

permissions: read-all

jobs:
  Ent_Tenant1:
    name: Test Ent_Tenant1
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    concurrency:
      group: aad
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Say Hello
        uses: ./.github/actions/say-hello
  Ent_Tenant2_G3:
    name: Test Ent_Tenant2_G3
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    concurrency:
      group: aad
      cancel-in-progress: false
    needs:
      - Ent_Tenant1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  Def_Tenant1:
    name: Test Def_Tenant1
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    concurrency:
      group: defender
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  Def_Tenant2_G3:
    name: Test Def_Tenant2_G3
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    concurrency:
      group: defender
      cancel-in-progress: false
    needs:
      - Def_Tenant1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
