# Purpose: Run unit tests for the code used in workflows and in actions

name: Unit Test Workflow

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  workflow-tests:
    name: Workflow Unit Tests
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Invoke workflow Pester tests
        run: |
          . utils/workflow/Invoke-PesterTests.ps1
          # Do not run the PSSA tests again, as they are part of
          # a previous test in the workflow
          Invoke-PesterTests -Path 'Testing/workflow' -ExcludePath 'utils/workflow/Invoke-PSSA.Tests.ps1'
  action-tests:
    name: Action Unit Tests
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Invoke action Pester tests
        run: |
          . utils/workflow/Invoke-PesterTests.ps1
          Invoke-PesterTests -Path 'Testing/action'
